### ISSUE TITLE
Improve how wind direction is captured 

### ISSUE THREAD

**Issue by Robdel12** [Robdel12/weatherstation#36]
Now that the wind direction is calibrated and accurate, it’s time to stop capturing “none” as a wind direction. Wil did a great job debugging and writing the firmware to  accurately capture the sensor data: https://gist.github.com/wwilsman/8cb9dc369f68053001002e1920d9bc49

**Comment by wwilsman** [comment]
#198 captures wind direction better and #226 does on-the-fly migration of old data 🎉
