### ISSUE TITLE
Calibrate wind direction

### ISSUE THREAD

**Issue by Robdel12** [Robdel12/weatherstation#6]
Currently the wind direction is not accurate and is not calibrated. 

@wwilsman where’s that gist at? 🤣

**Comment by wwilsman** [comment]
https://gist.github.com/wwilsman/8cb9dc369f68053001002e1920d9bc49

The APDS file is for the light sensor. If you haven't hooked that up yet you can delete the relevant light sensor code along with that file

**Comment by Robdel12** [comment]
Turns out it actually was. I do need to implement the better wind direction firmware you have though. Going to open a separate issues
